name: Deploy AWS Infra

on:
  push:
    branches: [ "main" ]

env:
  BUCKET_NAME: "mi-terraform-state-bucket"
  TF_STATE_KEY: "terraform.tfstate"
  AWS_REGION: "us-east-1"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Ensure S3 bucket exists
        run: |
          if ! aws s3 ls "s3://${{ env.BUCKET_NAME }}" 2>&1 >/dev/null; then
            echo "Bucket no existe, creando..."
            aws s3 mb "s3://${{ env.BUCKET_NAME }}"
          else
            echo "Bucket ya existe."
          fi

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (with S3 backend)
        working-directory: terraform
        run: |
          terraform init \
            -backend-config="bucket=${{ env.BUCKET_NAME }}" \
            -backend-config="key=${{ env.TF_STATE_KEY }}" \
            -backend-config="region=${{ env.AWS_REGION }}"

      - name: Terraform Plan (ALL .tf files)
        working-directory: terraform
        run: terraform plan

      - name: Terraform Apply (ALL .tf files)
        working-directory: terraform
        run: terraform apply -auto-approve
